# Generated by Django 5.0.1 on 2024-02-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='operating_system',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
