# Generated by Django 5.0.1 on 2024-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogs', '0002_ipaddress_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='cookies',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='host',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='method',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='path',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='referrer',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='session_data',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='user_agent',
            field=models.TextField(default='Unknown'),
        ),
    ]
