# Generated by Django 5.0.1 on 2024-02-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogs', '0003_ipaddress_cookies_ipaddress_host_ipaddress_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='os_specific',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
