# Generated by Django 5.0.1 on 2024-02-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplogs', '0004_ipaddress_os_specific'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='os_specific',
        ),
    ]
