# Generated by Django 5.0.1 on 2024-02-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogs', '0005_remove_ipaddress_operating_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
