# Generated by Django 5.0.1 on 2024-02-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplogs', '0006_ipaddress_latitude_ipaddress_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='meta_request',
            field=models.TextField(default='Unknown'),
        ),
    ]
